name: "smart_contracts_challenge"
version: "1.0.0"
config-version: 2

profile: "smart_contracts_challenge"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  smart_contracts_challenge:
    src:
      +materialized: ephemeral
    fct:
      +materialized: table
